# Generated by Django 4.2.2 on 2023-09-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Scope', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.TextField(blank=True, null=True)),
                ('DataType', models.TextField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalData', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('Emissions_t_of_CO2e', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('Scope_3_Indirect_Emissions', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('LifecycleEmissions', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('Floor_space_m2', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('EmissionsIntensity', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('CO2Emissions', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('CH4Emissions', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
                ('N2OEmissions', models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True)),
            ],
        ),
    ]
