# Generated by Django 4.2.2 on 2023-09-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alchimetis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CH4Emissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='CO2Emissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='EmissionsIntensity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Emissions_t_of_CO2e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Floor_space_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='LifecycleEmissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='N2OEmissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Scope_3_Indirect_Emissions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='TotalData',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
